server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: training-program-service
          uri: lb://training-program-service
          predicates:
            - Path=/api/training/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
