server:
  port: 8081

spring:
  application:
    name: training-program-service
  datasource:
    url: jdbc:mysql://localhost:3306/ett_training
    username: root
    password: ahmedP@ssW0rd0000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
